<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/tadah.proto

namespace App\Proto\Signal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Tadah.Signal.Thumbnail</code>
 */
class Thumbnail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Tadah.AssetType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>uint32 assetId = 2;</code>
     */
    protected $assetId = 0;
    /**
     * Generated from protobuf field <code>string accessKey = 3;</code>
     */
    protected $accessKey = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type int $assetId
     *     @type string $accessKey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Resources\Tadah::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Tadah.AssetType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.Tadah.AssetType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \App\Proto\AssetType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 assetId = 2;</code>
     * @return int
     */
    public function getAssetId()
    {
        return $this->assetId;
    }

    /**
     * Generated from protobuf field <code>uint32 assetId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAssetId($var)
    {
        GPBUtil::checkUint32($var);
        $this->assetId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string accessKey = 3;</code>
     * @return string
     */
    public function getAccessKey()
    {
        return $this->accessKey;
    }

    /**
     * Generated from protobuf field <code>string accessKey = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->accessKey = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Thumbnail::class, \App\Proto\Signal_Thumbnail::class);

