<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/tadah.proto

namespace App\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>Tadah.ClientVersion</code>
 */
class ClientVersion
{
    /**
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * Generated from protobuf enum <code>TAIPEI = 2011;</code>
     */
    const TAIPEI = 2011;
    /**
     * Generated from protobuf enum <code>TAMPA = 2016;</code>
     */
    const TAMPA = 2016;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::TAIPEI => 'TAIPEI',
        self::TAMPA => 'TAMPA',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

