<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/tadah.proto

namespace App\Proto;

if (false) {
    /**
     * This class is deprecated. Use App\Proto\Signal\Thumbnail instead.
     * @deprecated
     */
    class Signal_Thumbnail {}
}
class_exists(Signal\Thumbnail::class);
@trigger_error('App\Proto\Signal_Thumbnail is deprecated and will be removed in the next major release. Use App\Proto\Signal\Thumbnail instead', E_USER_DEPRECATED);

