<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/tadah.proto

namespace App\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Tadah.Signal</code>
 */
class Signal extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp nonce = 1;</code>
     */
    protected $nonce = null;
    /**
     * Generated from protobuf field <code>string jobId = 2;</code>
     */
    protected $jobId = '';
    /**
     * Generated from protobuf field <code>.Tadah.Operation operation = 3;</code>
     */
    protected $operation = 0;
    /**
     * Generated from protobuf field <code>.Tadah.ClientVersion version = 4;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>repeated .Tadah.Signal.Place place = 5;</code>
     */
    private $place;
    /**
     * Generated from protobuf field <code>repeated .Tadah.Signal.Thumbnail thumbnail = 6;</code>
     */
    private $thumbnail;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $nonce
     *     @type string $jobId
     *     @type int $operation
     *     @type int $version
     *     @type \App\Proto\Signal\Place[]|\Google\Protobuf\Internal\RepeatedField $place
     *     @type \App\Proto\Signal\Thumbnail[]|\Google\Protobuf\Internal\RepeatedField $thumbnail
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Resources\Tadah::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp nonce = 1;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getNonce()
    {
        return $this->nonce;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp nonce = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->nonce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string jobId = 2;</code>
     * @return string
     */
    public function getJobId()
    {
        return $this->jobId;
    }

    /**
     * Generated from protobuf field <code>string jobId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkString($var, True);
        $this->jobId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Tadah.Operation operation = 3;</code>
     * @return int
     */
    public function getOperation()
    {
        return $this->operation;
    }

    /**
     * Generated from protobuf field <code>.Tadah.Operation operation = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOperation($var)
    {
        GPBUtil::checkEnum($var, \App\Proto\Operation::class);
        $this->operation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Tadah.ClientVersion version = 4;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>.Tadah.ClientVersion version = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkEnum($var, \App\Proto\ClientVersion::class);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Tadah.Signal.Place place = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPlace()
    {
        return $this->place;
    }

    /**
     * Generated from protobuf field <code>repeated .Tadah.Signal.Place place = 5;</code>
     * @param \App\Proto\Signal\Place[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPlace($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Proto\Signal\Place::class);
        $this->place = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Tadah.Signal.Thumbnail thumbnail = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getThumbnail()
    {
        return $this->thumbnail;
    }

    /**
     * Generated from protobuf field <code>repeated .Tadah.Signal.Thumbnail thumbnail = 6;</code>
     * @param \App\Proto\Signal\Thumbnail[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setThumbnail($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Proto\Signal\Thumbnail::class);
        $this->thumbnail = $arr;

        return $this;
    }

}

