<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/tadah.proto

namespace App\Proto;

if (false) {
    /**
     * This class is deprecated. Use App\Proto\Signal\Place instead.
     * @deprecated
     */
    class Signal_Place {}
}
class_exists(Signal\Place::class);
@trigger_error('App\Proto\Signal_Place is deprecated and will be removed in the next major release. Use App\Proto\Signal\Place instead', E_USER_DEPRECATED);

